name: ViaPotions
version: ${version}
description: Translates thrown potions for ViaRewind
depend: [ProtocolLib]
api-version: 1.13
softdepend:
  - "ViaRewind"
  - "ViaRewind-Legacy-Support"
main: dev._2lstudios.viapotions.ViaPotions
